### PR TITLE
New feature hansford git assignment

### PR DESCRIPTION
**Pull request by zenwattage**
Scott Hansford Git Assignment Pull Request

### CODE REVIEW

**Comment by ZenSorcere** [comment]
I thought we'd agreed to go with Von's instead of Ralph's for the grocery store in the SceneOne re-write.

**Comment by nceres** [comment]
Ralph's has a better fuel discount program and they agreed to offer us store credit for a mention.

**Comment by ghost** [comment]
I really think we should go with an outdoor farmer's market to capture the mood of the scene.  The artificial lighting in a grocery store just won't do.

**Comment by zmagar** [comment]
It is the only kind of goodness which can survive the world in beautiful, magical, beautiful, wonderful and joyful love and life. It cannot be loved in fear of death, but to live up to its truest pleasure.

**Pull request closed without merging**
